name: FacelessItems
main: bw.development.facelessItems.FacelessItems
version: 1.0
api-version: 1.21
description: Plugin de ítems personalizados estilo EcoItems
author: cheinsowman

commands:
  giveitem:
    description: Da un ítem personalizado a un jugador
    usage: /giveitem <jugador> <item>
    permission: facelessitems.giveitem

  facelessitems:
    description: Comando principal para FacelessItems
    usage: /facelessitems <subcomando>
    permission: facelessitems.admin


permissions:
  facelessitems.giveitem:
    description: Permite usar el comando /giveitem
    default: op

  facelessitems.admin:
    description: Permite usar comandos administrativos
    default: op

